### PR TITLE
Fixes #96

### LINKED ISSUE #96: POST to hasMany relationship incorrectly includes empty 'attributes' objects
Per API spec here: http://jsonapi.org/format/#crud-updating-to-many-relationships

hasMany relationships can be bound via a POST action to the relationship URL:

implementation example (this is a sync action which adds all available 'devices' to a 'project')
```js
            addDevicesToProject() {
                this.startEvent();

                return new Promise((resolve, reject) => {
                    //const create = [];

                    const create = this.availableDevices.map((device) => {
                        return {type: 'devices', id: device.id}
                    });
                    JsonApi.one('project', this.project.id).all('device').post(create)
                        .then((responses) => {
                            this.successEvent(responses);
                            console.log('addDevices', responses);
                            resolve(responses);
                        })
                        .catch((error) => {
                            this.errorEvent(error);
                            reject(error);
                        });
                });
            }
```
In the above, the "create" const is prepared with an array of relationship objects. 

The prepared payload is:
```
{"data":[{"type":"devices","attributes":{},"id":"27"},{"type":"devices","attributes":{},"id":"28"}],"meta":{}}
```

The 'attributes' fields are unnecessary and cause problems.

I am testing with a version 2.0.3.

### PR DESCRIPTION
**Pull request by masimons**
### What changed:
We only want to include the attributes object if some attribute is defined, otherwise, we want to omit it from the payload.

### POSTing to a relationships route
Before fix: results in `400`
image

 After fix:
image

### CODE REVIEW

File: src/middleware/json-api/_serialize.js [hunk 1]
```diff
@@ -29,7 +29,14 @@ function resource (modelName, item) {
   })
 
   serializedResource.type = typeName
-  serializedResource.attributes = serializedAttributes
+
+  var attrValues = Object.keys(serializedAttributes).map(key => {
+    return serializedAttributes[key]
+  })
+
+  if (!!attrValues && attrValues.filter(val => val === undefined).length !== attrValues.length) {
```
Comment (masimons) [inline src/middleware/json-api/_serialize.js]: don't include `attributes` key if all attributes are `undefined`

**Comment by webandtech** [comment]
👍

File: src/middleware/json-api/_serialize.js (hunk 1 above)
Comment (mstahl) [reply src/middleware/json-api/_serialize.js]: It might be safer and more intention-revealing to do `Boolean(attrValues)` here instead of using `!!`.

Comment (masimons) [reply src/middleware/json-api/_serialize.js]: 👍

**Comment by EricSimons** [comment]
👍

File: test/api/serialize-test.js [hunk 2]
```diff
@@ -10,6 +10,15 @@ describe('serialize', () => {
     jsonApi = new JsonApi({apiUrl: 'http://myapi.com'})
   })
 
+  it('should not serialize undefined attributes', () => {
+    jsonApi.define('product', {
+      title: '',
+      about: ''
+    })
+    let serializedItem = serialize.resource.call(jsonApi, 'product', {title: undefined, about: undefined})
```
Comment (benjaminhoffman) [inline test/api/serialize-test.js]: `const serializedItem = ...`

**Comment by benjaminhoffman** [comment]
👍 but try instead:
```
if (Object.keys(serializedAttributes).length > 0) serializedResource.attributes = serializedAttributes
```
similar to how `serializedResource.relationships` is implemented, the above solution will return `undefined` for `.attributes` if `serializedAttributes` is an empty object.

**Comment by Emerson** [comment]
Great! Thanks for working on this <3
